<script setup>
import { ref, defineProps } from 'vue'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet'
import { GitPullRequest, Loader2 } from 'lucide-vue-next'

const props = defineProps({
  editorInstance: Object
})

const isOpen = ref(false)
const isLoading = ref(false)
const title = ref('Add Ultimate Automator E2E Tests')
const description = ref('Automated E2E tests generated by Ultimate Automator for improved test coverage and quality assurance.')
const successMessage = ref('')
const errorMessage = ref('')

function openPanel() {
  isOpen.value = true
  // Reset messages
  successMessage.value = ''
  errorMessage.value = ''
}

function closePanel() {
  isOpen.value = false
}

async function raisePR() {
  if (!props.editorInstance) {
    errorMessage.value = 'Editor instance not available'
    return
  }

  const code = props.editorInstance.getValue()
  if (!code.trim()) {
    errorMessage.value = 'No code to submit'
    return
  }

  isLoading.value = true
  errorMessage.value = ''
  successMessage.value = ''

  try {
    // Get userId from Chrome storage
    const result = await new Promise((resolve) => {
      chrome.storage.local.get('githubUserId', resolve)
    })

    const userId = result.githubUserId
    if (!userId) {
      throw new Error('No GitHub user ID found. Please connect your GitHub account first.')
    }

    const response = await fetch('http://localhost:3000/api/auth/github/create-pr', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        userId: userId,
        code: code,
        title: title.value,
        description: description.value
      })
    })

    const data = await response.json()

    if (data.success) {
      successMessage.value = `Pull request created successfully! View it at: ${data.data.pullRequestUrl}`
      // Auto close after 3 seconds
      setTimeout(() => {
        closePanel()
      }, 3000)
    } else {
      throw new Error(data.error || 'Failed to create pull request')
    }

  } catch (error) {
    console.error('Error creating PR:', error)
    errorMessage.value = error.message || 'Failed to create pull request'
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <Sheet v-model:open="isOpen">
    <!-- Trigger Button -->
    <SheetTrigger as-child>
      <Button 
        @click="openPanel" 
        variant="outline" 
        size="sm" 
        class="flex items-center gap-2 transition-all duration-200 hover:scale-105 hover:shadow-md"
      >
        <GitPullRequest class="w-4 h-4" />
        Raise PR
      </Button>
    </SheetTrigger>

    <!-- Sheet Content with smooth animation -->
    <SheetContent 
      side="right" 
      class="w-[400px] sm:w-[540px] flex flex-col p-0 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:slide-out-to-right data-[state=open]:slide-in-from-right duration-300"
    >
      <!-- Header -->
      <SheetHeader class="p-6 border-b bg-muted/20">
        <SheetTitle class="flex items-center gap-2 text-lg">
          <div class="p-2 bg-primary/10 rounded-lg">
            <GitPullRequest class="w-5 h-5 text-primary" />
          </div>
          Create Pull Request
        </SheetTitle>
        <SheetDescription class="text-sm text-muted-foreground">
          Submit your generated test code as a pull request to your repository
        </SheetDescription>
      </SheetHeader>

      <!-- Content -->
      <div class="flex-1 overflow-y-auto p-6 space-y-6">
        <Card class="border-0 shadow-sm">
          <CardHeader class="pb-4">
            <CardTitle class="text-base flex items-center gap-2">
              <div class="w-2 h-2 bg-blue-500 rounded-full"></div>
              Pull Request Details
            </CardTitle>
            <CardDescription class="text-sm">
              Customize your pull request information before submitting
            </CardDescription>
          </CardHeader>
          <CardContent class="space-y-4">
            <!-- Title Input with animation -->
            <div class="space-y-2 group">
              <Label htmlFor="pr-title" class="text-sm font-medium">Title</Label>
              <Input
                id="pr-title"
                v-model="title"
                placeholder="Enter PR title"
                class="transition-all duration-200 focus:ring-2 focus:ring-primary/20 focus:border-primary group-hover:border-primary/50"
              />
            </div>

            <!-- Description Textarea with animation -->
            <div class="space-y-2 group">
              <Label htmlFor="pr-description" class="text-sm font-medium">Description</Label>
              <Textarea
                id="pr-description"
                v-model="description"
                placeholder="Enter PR description"
                class="min-h-[120px] resize-none transition-all duration-200 focus:ring-2 focus:ring-primary/20 focus:border-primary group-hover:border-primary/50"
                rows="5"
              />
            </div>

            <!-- Success Message with slide animation -->
            <Transition 
              enter-active-class="transition-all duration-300 ease-out"
              enter-from-class="opacity-0 transform translate-y-2"
              enter-to-class="opacity-100 transform translate-y-0"
              leave-active-class="transition-all duration-200 ease-in"
              leave-from-class="opacity-100 transform translate-y-0"
              leave-to-class="opacity-0 transform translate-y-2"
            >
              <div v-if="successMessage" class="p-4 bg-green-50 border border-green-200 rounded-lg">
                <div class="flex items-start gap-2">
                  <div class="w-5 h-5 text-green-600 mt-0.5">
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                    </svg>
                  </div>
                  <p class="text-sm text-green-800 leading-relaxed">{{ successMessage }}</p>
                </div>
              </div>
            </Transition>

            <!-- Error Message with slide animation -->
            <Transition 
              enter-active-class="transition-all duration-300 ease-out"
              enter-from-class="opacity-0 transform translate-y-2"
              enter-to-class="opacity-100 transform translate-y-0"
              leave-active-class="transition-all duration-200 ease-in"
              leave-from-class="opacity-100 transform translate-y-0"
              leave-to-class="opacity-0 transform translate-y-2"
            >
              <div v-if="errorMessage" class="p-4 bg-red-50 border border-red-200 rounded-lg">
                <div class="flex items-start gap-2">
                  <div class="w-5 h-5 text-red-600 mt-0.5">
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                    </svg>
                  </div>
                  <p class="text-sm text-red-800 leading-relaxed">{{ errorMessage }}</p>
                </div>
              </div>
            </Transition>
          </CardContent>
        </Card>
      </div>

      <!-- Footer with animated buttons -->
      <div class="p-6 border-t bg-muted/20">
        <div class="flex gap-3">
          <Button 
            @click="closePanel" 
            variant="outline" 
            class="flex-1 transition-all duration-200 hover:bg-muted hover:scale-105"
          >
            Cancel
          </Button>
          <Button 
            @click="raisePR" 
            :disabled="isLoading || !title.trim()" 
            class="flex-1 transition-all duration-200 hover:scale-105 disabled:hover:scale-100"
            :class="isLoading ? 'animate-pulse' : ''"
          >
            <Transition
              enter-active-class="transition-all duration-200"
              leave-active-class="transition-all duration-200"
              enter-from-class="opacity-0 scale-50"
              enter-to-class="opacity-100 scale-100"
              leave-from-class="opacity-100 scale-100"
              leave-to-class="opacity-0 scale-50"
              mode="out-in"
            >
              <div v-if="isLoading" class="flex items-center gap-2">
                <Loader2 class="w-4 h-4 animate-spin" />
                Creating...
              </div>
              <div v-else class="flex items-center gap-2">
                <GitPullRequest class="w-4 h-4" />
                Create PR
              </div>
            </Transition>
          </Button>
        </div>
      </div>
    </SheetContent>
  </Sheet>
</template>
