<script setup>
import { ref, defineProps } from 'vue'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet'
import { GitPullRequest, Loader2, Eye, Edit } from 'lucide-vue-next'

const props = defineProps({
  editorInstance: Object
})

const isOpen = ref(false)
const isLoading = ref(false)
const title = ref('Add Ultimate Automator E2E Tests')
const description = ref(`## Ultimate Automator E2E Tests

This pull request adds automated end-to-end tests generated by Ultimate Automator for improved test coverage and quality assurance.

### What's included:
- ✅ Generated Playwright test code
- ✅ Test coverage for key user flows
- ✅ Automated quality checks

### Benefits:
- Improved test coverage
- Automated regression testing
- Better code quality assurance

### Testing:
Run the tests using: \`npm run test\` or \`npx playwright test\``)

const successMessage = ref('')
const errorMessage = ref('')
const isPreviewMode = ref(false)
const showSuccessPopup = ref(false)
const prDetails = ref(null)

function openPanel() {
  isOpen.value = true
  // Reset messages
  successMessage.value = ''
  errorMessage.value = ''
}

function closePanel() {
  isOpen.value = false
}

function togglePreview() {
  isPreviewMode.value = !isPreviewMode.value
}

// Simple markdown to HTML converter for preview
function markdownToHtml(markdown) {
  return markdown
    .replace(/^### (.*$)/gim, '<h3 class="text-lg font-semibold mt-4 mb-2">$1</h3>')
    .replace(/^## (.*$)/gim, '<h2 class="text-xl font-bold mt-6 mb-3">$1</h2>')
    .replace(/^# (.*$)/gim, '<h1 class="text-2xl font-bold mt-8 mb-4">$1</h1>')
    .replace(/\*\*(.*)\*\*/gim, '<strong class="font-semibold">$1</strong>')
    .replace(/\*(.*)\*/gim, '<em class="italic">$1</em>')
    .replace(/`([^`]+)`/gim, '<code class="bg-muted px-1 py-0.5 rounded text-sm font-mono">$1</code>')
    .replace(/^- (.*$)/gim, '<li class="ml-4">• $1</li>')
    .replace(/^✅ (.*$)/gim, '<li class="ml-4 text-green-600">✅ $1</li>')
    .replace(/\n/gim, '<br>')
}

async function raisePR() {
  if (!props.editorInstance) {
    errorMessage.value = 'Editor instance not available'
    return
  }

  const code = props.editorInstance.getValue()
  if (!code.trim()) {
    errorMessage.value = 'No code to submit'
    return
  }

  isLoading.value = true
  errorMessage.value = ''
  successMessage.value = ''

  try {
    // Get userId from Chrome storage
    const result = await new Promise((resolve) => {
      chrome.storage.local.get('githubUserId', resolve)
    })

    const userId = result.githubUserId
    if (!userId) {
      throw new Error('No GitHub user ID found. Please connect your GitHub account first.')
    }

    const response = await fetch('http://localhost:3000/api/auth/github/create-pr', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        userId: userId,
        code: code,
        title: title.value,
        description: description.value
      })
    })

    const data = await response.json()

    if (data.success) {
      // Store PR details for popup
      prDetails.value = data.data
      showSuccessPopup.value = true
      
      // Close the main sheet
      setTimeout(() => {
        closePanel()
      }, 500)
    } else {
      throw new Error(data.error || 'Failed to create pull request')
    }

  } catch (error) {
    console.error('Error creating PR:', error)
    errorMessage.value = error.message || 'Failed to create pull request'
  } finally {
    isLoading.value = false
  }
}

function openPR() {
  if (prDetails.value?.pullRequestUrl) {
    window.open(prDetails.value.pullRequestUrl, '_blank')
  }
  closeSuccessPopup()
}

function createAnotherPR() {
  closeSuccessPopup()
  // Reset form and reopen
  setTimeout(() => {
    openPanel()
  }, 300)
}

function closeSuccessPopup() {
  showSuccessPopup.value = false
  prDetails.value = null
}
</script>

<template>
  <!-- Main Sheet -->
  <Sheet v-model:open="isOpen">
    <!-- Trigger Button -->
    <SheetTrigger as-child>
      <Button 
        @click="openPanel" 
        variant="outline" 
        size="sm" 
        class="flex items-center gap-2 transition-all duration-200 hover:scale-105 hover:shadow-md"
      >
        <GitPullRequest class="w-4 h-4" />
        Raise PR
      </Button>
    </SheetTrigger>

    <!-- Sheet Content with forced increased width -->
    <SheetContent 
      side="right" 
      class="flex flex-col p-0 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:slide-out-to-right data-[state=open]:slide-in-from-right duration-300"
      style="width: 800px !important; max-width: 800px !important;"
    >
      <!-- Header -->
      <SheetHeader class="p-6 border-b bg-muted/20">
        <SheetTitle class="flex items-center gap-2 text-lg">
          <div class="p-2 bg-primary/10 rounded-lg">
            <GitPullRequest class="w-5 h-5 text-primary" />
          </div>
          Create Pull Request
        </SheetTitle>
        <SheetDescription class="text-sm text-muted-foreground">
          Submit your generated test code as a pull request to your repository
        </SheetDescription>
      </SheetHeader>

      <!-- Content -->
      <div class="flex-1 overflow-y-auto p-6 space-y-6">
        <Card class="border-0 shadow-sm">
          <CardHeader class="pb-4">
            <CardTitle class="text-base flex items-center gap-2">
              <div class="w-2 h-2 bg-blue-500 rounded-full"></div>
              Pull Request Details
            </CardTitle>
            <CardDescription class="text-sm">
              Customize your pull request information before submitting
            </CardDescription>
          </CardHeader>
          <CardContent class="space-y-6">
            <!-- Title Input with animation -->
            <div class="space-y-2 group">
              <Label htmlFor="pr-title" class="text-sm font-medium">Title</Label>
              <Input
                id="pr-title"
                v-model="title"
                placeholder="Enter PR title"
                class="transition-all duration-200 focus:ring-2 focus:ring-primary/20 focus:border-primary group-hover:border-primary/50"
              />
            </div>

            <!-- Description with Markdown Editor -->
            <div class="space-y-3 group">
              <div class="flex items-center justify-between">
                <Label htmlFor="pr-description" class="text-sm font-medium">Description (Markdown)</Label>
                <Button
                  @click="togglePreview"
                  variant="ghost"
                  size="sm"
                  class="h-8 px-2 text-xs"
                >
                  <Eye v-if="!isPreviewMode" class="w-3 h-3 mr-1" />
                  <Edit v-else class="w-3 h-3 mr-1" />
                  {{ isPreviewMode ? 'Edit' : 'Preview' }}
                </Button>
              </div>
              
              <!-- Markdown Editor -->
              <div v-if="!isPreviewMode" class="relative">
                <Textarea
                  id="pr-description"
                  v-model="description"
                  placeholder="Enter PR description in markdown format"
                  class="min-h-[300px] resize-none transition-all duration-200 focus:ring-2 focus:ring-primary/20 focus:border-primary group-hover:border-primary/50 font-mono text-sm"
                  rows="12"
                />
                <div class="absolute bottom-2 right-2 text-xs text-muted-foreground bg-background px-2 py-1 rounded border">
                  Markdown supported
                </div>
              </div>

              <!-- Markdown Preview -->
              <div v-else class="min-h-[300px] p-4 border rounded-md bg-muted/30">
                <div 
                  class="prose prose-sm max-w-none text-sm leading-relaxed"
                  v-html="markdownToHtml(description)"
                ></div>
              </div>

              <!-- Markdown Help -->
              <div class="text-xs text-muted-foreground bg-muted/50 p-3 rounded-md">
                <strong>Markdown tips:</strong> 
                Use **bold**, *italic*, `code`, # Headers, - Lists, ✅ Checkmarks
              </div>
            </div>

            <!-- Success Message with slide animation -->
            <Transition 
              enter-active-class="transition-all duration-300 ease-out"
              enter-from-class="opacity-0 transform translate-y-2"
              enter-to-class="opacity-100 transform translate-y-0"
              leave-active-class="transition-all duration-200 ease-in"
              leave-from-class="opacity-100 transform translate-y-0"
              leave-to-class="opacity-0 transform translate-y-2"
            >
              <div v-if="successMessage" class="p-4 bg-green-50 border border-green-200 rounded-lg">
                <div class="flex items-start gap-2">
                  <div class="w-5 h-5 text-green-600 mt-0.5">
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                    </svg>
                  </div>
                  <p class="text-sm text-green-800 leading-relaxed">{{ successMessage }}</p>
                </div>
              </div>
            </Transition>

            <!-- Error Message with slide animation -->
            <Transition 
              enter-active-class="transition-all duration-300 ease-out"
              enter-from-class="opacity-0 transform translate-y-2"
              enter-to-class="opacity-100 transform translate-y-0"
              leave-active-class="transition-all duration-200 ease-in"
              leave-from-class="opacity-100 transform translate-y-0"
              leave-to-class="opacity-0 transform translate-y-2"
            >
              <div v-if="errorMessage" class="p-4 bg-red-50 border border-red-200 rounded-lg">
                <div class="flex items-start gap-2">
                  <div class="w-5 h-5 text-red-600 mt-0.5">
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                    </svg>
                  </div>
                  <p class="text-sm text-red-800 leading-relaxed">{{ errorMessage }}</p>
                </div>
              </div>
            </Transition>
          </CardContent>
        </Card>
      </div>

      <!-- Footer with animated buttons -->
      <div class="p-6 border-t bg-muted/20">
        <div class="flex gap-3">
          <Button 
            @click="closePanel" 
            variant="outline" 
            class="flex-1 transition-all duration-200 hover:bg-muted hover:scale-105"
          >
            Cancel
          </Button>
          <Button 
            @click="raisePR" 
            :disabled="isLoading || !title.trim()" 
            class="flex-1 transition-all duration-200 hover:scale-105 disabled:hover:scale-100"
            :class="isLoading ? 'animate-pulse' : ''"
          >
            <Transition
              enter-active-class="transition-all duration-200"
              leave-active-class="transition-all duration-200"
              enter-from-class="opacity-0 scale-50"
              enter-to-class="opacity-100 scale-100"
              leave-from-class="opacity-100 scale-100"
              leave-to-class="opacity-0 scale-50"
              mode="out-in"
            >
              <div v-if="isLoading" class="flex items-center gap-2">
                <Loader2 class="w-4 h-4 animate-spin" />
                Creating...
              </div>
              <div v-else class="flex items-center gap-2">
                <GitPullRequest class="w-4 h-4" />
                Create PR
              </div>
            </Transition>
          </Button>
        </div>
      </div>
    </SheetContent>
  </Sheet>

  <!-- Success Popup -->
  <div 
    v-if="showSuccessPopup" 
    class="fixed inset-0 bg-black/60 backdrop-blur-sm z-[100] flex items-center justify-center p-4"
    @click="closeSuccessPopup"
  >
    <div 
      class="bg-background rounded-2xl shadow-2xl max-w-md w-full p-0 transform transition-all duration-300 scale-100 animate-in slide-in-from-bottom-4"
      @click.stop
    >
      <!-- Success Header -->
      <div class="bg-gradient-to-r from-green-50 to-emerald-50 p-6 rounded-t-2xl border-b">
        <div class="flex items-center gap-3">
          <div class="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center">
            <svg class="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
            </svg>
          </div>
          <div>
            <h3 class="text-lg font-semibold text-green-800">Pull Request Created!</h3>
            <p class="text-sm text-green-600">Your code has been successfully submitted</p>
          </div>
        </div>
      </div>

      <!-- PR Details -->
      <div class="p-6 space-y-4">
        <div class="bg-muted/30 rounded-lg p-4 space-y-3">
          <div class="flex items-center gap-2">
            <GitPullRequest class="w-4 h-4 text-blue-600" />
            <span class="font-medium text-sm">PR Details</span>
          </div>
          
          <div class="space-y-2 text-sm">
            <div class="flex justify-between">
              <span class="text-muted-foreground">PR Number:</span>
              <span class="font-mono bg-background px-2 py-1 rounded">
                #{{ prDetails?.pullRequestNumber }}
              </span>
            </div>
            
            <div class="flex justify-between">
              <span class="text-muted-foreground">Branch:</span>
              <span class="font-mono bg-background px-2 py-1 rounded text-xs">
                {{ prDetails?.branchName }}
              </span>
            </div>
            
            <div class="flex justify-between">
              <span class="text-muted-foreground">File:</span>
              <span class="font-mono bg-background px-2 py-1 rounded text-xs">
                {{ prDetails?.fileName }}
              </span>
            </div>
          </div>
        </div>

        <!-- Celebration Animation -->
        <div class="flex justify-center py-2">
          <div class="flex space-x-1">
            <div class="animate-bounce" style="animation-delay: 0ms;">🎉</div>
            <div class="animate-bounce" style="animation-delay: 100ms;">✨</div>
            <div class="animate-bounce" style="animation-delay: 200ms;">🚀</div>
            <div class="animate-bounce" style="animation-delay: 300ms;">✨</div>
            <div class="animate-bounce" style="animation-delay: 400ms;">🎉</div>
          </div>
        </div>

        <!-- Action Buttons -->
        <div class="space-y-3">
          <Button 
            @click="openPR" 
            class="w-full bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg hover:shadow-xl transition-all duration-200 transform hover:scale-105"
          >
            <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"></path>
            </svg>
            Open Pull Request
          </Button>
          
          <div class="flex gap-2">
            <Button 
              @click="createAnotherPR" 
              variant="outline" 
              class="flex-1 hover:bg-muted transition-all duration-200"
            >
              <GitPullRequest class="w-4 h-4 mr-2" />
              Create Another
            </Button>
            
            <Button 
              @click="closeSuccessPopup" 
              variant="ghost" 
              class="flex-1 hover:bg-muted transition-all duration-200"
            >
              Done
            </Button>
          </div>
        </div>
      </div>

      <!-- Decorative Elements -->
      <div class="absolute -top-2 -right-2 w-4 h-4 bg-green-400 rounded-full animate-ping"></div>
      <div class="absolute -top-1 -right-1 w-2 h-2 bg-green-500 rounded-full"></div>
    </div>
  </div>
</template>

<style scoped>
/* Custom prose styles for markdown preview */
.prose h1, .prose h2, .prose h3 {
  color: hsl(var(--foreground));
}

.prose code {
  background-color: hsl(var(--muted));
  color: hsl(var(--foreground));
}

.prose li {
  margin: 0.25rem 0;
}

/* Force the sheet width to override any default constraints */
:deep([data-radix-dialog-content]) {
  width: 800px !important;
  max-width: 800px !important;
}

/* Alternative approach - target the sheet content directly */
:deep(.sheet-content) {
  width: 800px !important;
  max-width: 800px !important;
}

/* Custom animations for success popup */
@keyframes slide-in-from-bottom-4 {
  from {
    transform: translateY(1rem);
    opacity: 0;
  }
  to {
    transform: translateY(0);
    opacity: 1;
  }
}

.animate-in {
  animation-duration: 0.3s;
  animation-fill-mode: both;
}

.slide-in-from-bottom-4 {
  animation-name: slide-in-from-bottom-4;
}

/* Backdrop blur effect */
.backdrop-blur-sm {
  backdrop-filter: blur(4px);
}
</style>
